name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        uv-version: 'latest' # or a specific version like '0.1.2'
        enable-cache: true

    - name: Install dependencies
      run: uv sync # Installs dependencies based on pyproject.toml or requirements.txt

    ##- name: Run tests
    ##  run: uv run pytest

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{secrets.ACR_REGISTER}} # Replace with your ACR login server
        username: ${{ secrets.ACR_USERNAME }} # Store ACR username as a secret
        password: ${{ secrets.ACR_PASSWORD }} # Store ACR password or Service Principal password as a secret


    - name: Build and Push the Docker Image
      uses: docker/setup-buildx-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
