name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, ubuntu-8gb-ash-2]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run application with environment variables
      env:
        API_KEY: ${{ secrets.MY_API_KEY }} # Accessing a GitHub secret
        APP_ENV: production
      run: python -m uvicorn src.main:app --host 0.0.0.0 --port 8000
